apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: videostream
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: jvieira22/videostream
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default

  source:
    repoURL: https://github.com/jonvieirac/sd_phpsite.git
    path: dev
    targetRevision: HEAD
  destination: 
    server: https://kubernetes.default.svc
    namespace: sdapp

  syncPolicy: 
    automated:
      selfHeal: true
      prune: true
