apiVersion: apps/v1
kind: Deployment
metadata:
  name: videostream
  namespace: sdapp
  labels:
    app: videostream
  annotations:
    argocd-image-updater.argoproj.io/image-list: jvieira22/videostream
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  replicas: 2
  selector:
    matchLabels:
      app: videostream
  template:
    metadata:
      labels:
        app: videostream
    spec:
      containers:
      - name: videostream
        image: jvieira22/videostream:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: videostream
  namespace: sdapp
  labels:
    app: videostream
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30001
  selector:
    app: videostream
