name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: 
        docker build -t videostream:v1 .
        docker login -u jvieira22 -p dckr_pat_Z4ngVxoZVNDnEoKpqbNArlCcgQE
        docker tag app jvieira22/videostream
        docker push jvieira22/videostream
      
